# Generated by Django 5.1.7 on 2026-03-27 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detector", "0002_chatmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobprediction",
            name="probability",
        ),
    ]
